name: Ping Bot
on:
  schedule:
    - cron: '*/5 * * * *' # Exécute toutes les 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        run: |
          curl -X GET https://your-bot-url.onrender.com
